M48
; DRILL file {KiCad 8.0.2} date 2024-10-03T22:03:04+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-03T22:03:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.050
%
G90
G05
T1
X93.094Y-106.906
T2
X90.406Y-109.594
M30
